version: '3.7'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
      - 5000:5000
    container_name: jenkins
    volumes:
      - /home/ubuntu/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock