apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: react-app

spec:
  template:
    metadata:
      name: pod-react-app
      labels:
        env: production
    spec:
      containers:
        - name: react-app
          image: nodeapp:latest
      ports:
        - 80:80
  selector:
    matchLabels:
      env: production
  replicas: 2